spring.application.name=hvb-backend

# Conexion al PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Servidor
server.port=8080
server.address=0.0.0.0

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=-1

# Correo Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=hvbistro2026@gmail.com
spring.mail.password=vvfvdpmwghzbujke
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


spring.jpa.open-in-view=false

### Credenciales de Google Wallet ###
**/wallet-credentials.json
src/main/resources/wallet-credentials.json

# Google Wallet
google.wallet.issuer-id=3388000000023164504
google.wallet.credentials-path=classpath:wallet-credentials.json

supabase.url=https://nalfdzbjlnuuzinuwvzo.supabase.co
supabase.service-role-key=sb_secret_2RqaaXrmLyEGWAZfKSXNAA_TOIb6YpF
supabase.storage.bucket=wallet-assets

resend.api-key=re_FHAna74q_EjA3u2bjVjTStZNRAi9euFCL
resend.from-email=onboarding@resend.dev
app.frontend-url=http://localhost:5173

